<a href="https://colab.research.google.com/github/Priyanshu456574/Capstone-Project/blob/main/Data_processing_level_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('/content/gurgaon_properties.csv')

In [ ]:
df.sample(5)

,property_name,property_type,society,price,price_per_sqfeet,area,areaWithType,bedRoom,bathroom,balcony,...,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,price_per_sqft
3139,4 Bedroom House for sale in Nirvana Country,house,unitech espace,7.35,NaN,1760.0,Plot area 240(200.67 sq.m.),4,4,3+,...,"Nirvana Country, Gurgaon, Haryana",3.0,South,5 to 10 Year Old,"['Radhakrishna Shani Mandir', 'Sri Radhe Krish...",This is property is next to park and sunfacing.,"['5 Wardrobe', '1 Exhaust Fan', '4 Geyser', '9...","['High Ceiling Height', 'Maintenance Staff', '...","['Environment5 out of 5', 'Lifestyle5 out of 5...",41762.0
3246,6 Bedroom House for sale in Sector 22 Gurgaon,house,saksham welfare association,4.70,NaN,2368.0,Plot area 220Built Up area: 170 sq.m.Carpet ar...,6,6,3+,...,"Sector 22, Sector 22 Gurgaon, Gurgaon, Haryana",2.0,West,10+ Year Old,"['HUDA Sector 23 Market', 'Palam triangle', 'J...",One of the best location in sector fully devel...,"['1 Fan', '1 Exhaust Fan', '2 Geyser', '1 Chim...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment4 out of 5', 'Safety5 out of 5', ...",19847.0
460,3 BHK Flat in Sector 1 Imt Manesar,flats,hsiidc sidco aravali,0.91,3516.0,2588.0,Super Built up area 2588(240.43 sq.m.)Built Up...,3,3,3+,...,"Sector 1 Imt Manesar, Gurgaon, Haryana",8.0,East,5 to 10 Year Old,"['Pooja Clinic', 'Dr. Sahil Clinic', 'Prakash ...",Arawali sidco good property imt manesar \nNear...,"['6 Fan', '6 Light', 'No AC', 'No Bed', 'No Ch...","['Power Back-up', 'Lift(s)', 'Maintenance Staf...","['Environment5 out of 5', 'Lifestyle4.5 out of...",NaN
349,3 BHK Flat in Sector 69 Gurgaon,flats,tulip violet,1.36,8841.0,1538.0,Super Built up area 1538(142.88 sq.m.),3,3,1,...,"12th Floor, Sector 69 Gurgaon, Gurgaon, Haryana",12.0,North-West,1 to 5 Year Old,"['Airia Mall Sector 68', 'Southern Peripheral ...",Best price in tulip violet \nSun facing\nPark ...,"['1 Modular Kitchen', 'No AC', 'No Bed', 'No C...","['Power Back-up', 'Feng Shui / Vaastu Complian...","['Green Area5 out of 5', 'Construction4 out of...",NaN
534,3 BHK Flat in Sector 32 Gurgaon,flats,aqua front towers,2.50,11715.0,2134.0,Built Up area: 2134 (198.26 sq.m.)Carpet area:...,3,4,3+,...,"Sohna Sector 32, Sector 32 Gurgaon, Gurgaon, H...",1.0,NaN,undefined,NaN,Best in class property available at sector 32 ...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,NaN,NaN

In [ ]:
df.shape

(3961, 21)

In [ ]:
df = df.iloc[:, :-1]

In [ ]:
df.sample(5)

,property_name,property_type,society,price,price_per_sqfeet,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
1863,4 BHK Flat in Sector 69 Gurgaon,flats,tulip violet,3.25,10105.0,3216.0,Super Built up area 3216(298.78 sq.m.),4,5,3+,"pooja room,others","Sector 69 Gurgaon, Gurgaon, Haryana",14.0,NaN,1 to 5 Year Old,"['Airia Mall Sector 68', 'Southern Peripheral ...",Beautiful penthouse in premium tower with l vi...,[],"['Feng Shui / Vaastu Compliant', 'Intercom Fac...","['Green Area5 out of 5', 'Construction4 out of..."
1300,2 BHK Flat in Sector 71 Gurgaon,flats,signature andour heights,0.60,10000.0,600.0,Super Built up area 600(55.74 sq.m.)Carpet are...,2,2,1,pooja room,"001, Sector 71 Gurgaon, Gurgaon, Haryana",5.0,South-West,1 to 5 Year Old,"['Bigbasket SPR 5K DS', 'iON Digital Zone, DPG...",This is 2bhk semi furnished flat available on ...,NaN,"['Security / Fire Alarm', 'Lift(s)', 'Maintena...","['Green Area5 out of 5', 'Construction4.5 out ..."
3809,2 BHK Flat in Sector 95 Gurgaon,flats,ramsons kshitij,0.32,4500.0,711.0,Super Built up area 700(65.03 sq.m.)Carpet are...,2,2,1,others,"Sector 95 Gurgaon, Gurgaon, Haryana",8.0,NaN,1 to 5 Year Old,"['Bangali Clinic', 'Yadav Clinic', 'Dr. J. S. ...","Fully furnished 2bhk apartment, on main pataud...","['1 Water Purifier', '3 Fan', '1 Fridge', '1 D...","['Feng Shui / Vaastu Compliant', 'Intercom Fac...","['Green Area4 out of 5', 'Amenities4 out of 5'..."
3753,3 Bedroom House for sale in Rajendra Park,house,Independent,0.65,NaN,720.0,Plot area 80(66.89 sq.m.),3,2,1,"pooja room,others","Rajendra Park, Gurgaon, Haryana",1.0,East,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Dr. ...",Near by dwarka express way near by railways st...,NaN,"['Water Storage', 'Visitor Parking']","['Environment4 out of 5', 'Lifestyle4 out of 5..."
2473,3 BHK Flat in Sector 70 Gurgaon,flats,shree vardhman victoria,1.80,9230.0,1950.0,Super Built up area 1950(181.16 sq.m.)Carpet a...,3,4,3,"servant room,others","Sector 70 Gurgaon, Gurgaon, Haryana",2.0,South-West,0 to 1 Year Old,"['Airia Mall', 'Golf Course Extn Road', 'Sohna...",With 2 covered car parking and main central pa...,[],"['Feng Shui / Vaastu Compliant', 'Intercom Fac...","['Management4.5 out of 5', 'Green Area5 out of..."

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3961 entries, 0 to 3960
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   property_name     3961 non-null   object
 1   property_type     3961 non-null   object
 2   society           3960 non-null   object
 3   price             3941 non-null   float64
 4   price_per_sqfeet  2996 non-null   float64
 5   area              3941 non-null   float64
 6   areaWithType      3961 non-null   object
 7   bedRoom           3961 non-null   int64
 8   bathroom          3961 non-null   int64
 9   balcony           3961 non-null   object
 10  additionalRoom    3961 non-null   object
 11  address           3950 non-null   object
 12  floorNum          3940 non-null   float64
 13  facing            2784 non-null   object
 14  agePossession     3960 non-null   object
 15  nearbyLocations   3754 non-null   object
 16  description       3961 non-null   object
 17  furnishDetails    2929 non-null   object
 18  features          3252 non-null   object
 19  rating            3511 non-null   object
dtypes: float64(4), int64(2), object(14)
memory usage: 619.0+ KB

In [ ]:
df.isnull().sum()

property_name          0
property_type          0
society                1
price                 20
price_per_sqfeet     965
area                  20
areaWithType           0
bedRoom                0
bathroom               0
balcony                0
additionalRoom         0
address               11
floorNum              21
facing              1177
agePossession          1
nearbyLocations      207
description            0
furnishDetails      1032
features             709
rating               450
dtype: int64

In [ ]:
df.head()

,property_name,property_type,society,price,price_per_sqfeet,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 109 Gurgaon,house,international city by sobha phase 2,7.00,NaN,5400.0,Plot area 600(501.68 sq.m.),5,6,2,servant room,"141, Sector 109 Gurgaon, Gurgaon, Haryana",2.0,West,1 to 5 Year Old,"['Dwarka Sector 21 Metro Station', 'Pacific D2...","Peaceful, private, premium, gated, duplex vill...",NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,2 BHK Flat in Sohna,flats,breez global hill view,0.35,5600.0,625.0,Carpet area: 625 (58.06 sq.m.),2,2,2,not_available,"Sohna, Gurgaon, Haryana",14.0,NaN,1 to 5 Year Old,"['Huda City Centre', 'Omaxe City Centre', 'Nin...","Spacious rooms, well maintained facilities, ri...","['3 Fan', '1 Exhaust Fan', '4 Light', '1 Curta...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
2,2 BHK Flat in Sector-33 Sohna,flats,godrej nature plus,1.07,7725.0,1385.0,Super Built up area 1385(128.67 sq.m.),2,2,2,not_available,"Sector-33 Sohna, Gurgaon, Haryana",14.0,North-East,2023-08-01 00:00:00,"['Signature Global Infinity Mall Sohna', 'Bads...",We are the proud owners of this 2 bhk apartmen...,[],"['Lift(s)', 'Maintenance Staff', 'Water Storag...",NaN
3,4 BHK Flat in Sector 60 Gurgaon,flats,ireo skyon,3.60,12815.0,2809.0,Super Built up area 2809(260.96 sq.m.)Carpet a...,4,5,3,servant room,"Sector 60 Gurgaon, Gurgaon, Haryana",24.0,North-East,1 to 5 Year Old,"['Sector 55-56 Metro', 'Golf Course Extension'...","This 4 bhk flat is located in ireo skyon, whic...","['7 Wardrobe', '1 Water Purifier', '6 Fan', '1...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction5 out of..."
4,4 BHK Flat in Sector 72 Gurgaon,flats,tata primanti,4.00,16032.0,2495.0,Super Built up area 2905(269.88 sq.m.)Carpet a...,4,5,3+,servant room,"2204, Sector 72 Gurgaon, Gurgaon, Haryana",22.0,West,1 to 5 Year Old,"['Sector 55-56 Metro Station', 'Omaxe City Cen...",This lovely 4 bhk apartment/flat in sector 72 ...,"['1 Water Purifier', '1 Exhaust Fan', '6 Geyse...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area4 out of 5', 'Construction4 out of..."

In [ ]:
df.insert(loc=3,column='sector',value=df['property_name'].str.split('in').str.get(1).str.replace('Gurgaon','').str.strip())

In [ ]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqfeet,area,areaWithType,bedRoom,bathroom,...,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 109 Gurgaon,house,international city by sobha phase 2,Sector 109,7.00,NaN,5400.0,Plot area 600(501.68 sq.m.),5,6,...,servant room,"141, Sector 109 Gurgaon, Gurgaon, Haryana",2.0,West,1 to 5 Year Old,"['Dwarka Sector 21 Metro Station', 'Pacific D2...","Peaceful, private, premium, gated, duplex vill...",NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,2 BHK Flat in Sohna,flats,breez global hill view,Sohna,0.35,5600.0,625.0,Carpet area: 625 (58.06 sq.m.),2,2,...,not_available,"Sohna, Gurgaon, Haryana",14.0,NaN,1 to 5 Year Old,"['Huda City Centre', 'Omaxe City Centre', 'Nin...","Spacious rooms, well maintained facilities, ri...","['3 Fan', '1 Exhaust Fan', '4 Light', '1 Curta...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
2,2 BHK Flat in Sector-33 Sohna,flats,godrej nature plus,Sector-33 Sohna,1.07,7725.0,1385.0,Super Built up area 1385(128.67 sq.m.),2,2,...,not_available,"Sector-33 Sohna, Gurgaon, Haryana",14.0,North-East,2023-08-01 00:00:00,"['Signature Global Infinity Mall Sohna', 'Bads...",We are the proud owners of this 2 bhk apartmen...,[],"['Lift(s)', 'Maintenance Staff', 'Water Storag...",NaN
3,4 BHK Flat in Sector 60 Gurgaon,flats,ireo skyon,Sector 60,3.60,12815.0,2809.0,Super Built up area 2809(260.96 sq.m.)Carpet a...,4,5,...,servant room,"Sector 60 Gurgaon, Gurgaon, Haryana",24.0,North-East,1 to 5 Year Old,"['Sector 55-56 Metro', 'Golf Course Extension'...","This 4 bhk flat is located in ireo skyon, whic...","['7 Wardrobe', '1 Water Purifier', '6 Fan', '1...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction5 out of..."
4,4 BHK Flat in Sector 72 Gurgaon,flats,tata primanti,Sector 72,4.00,16032.0,2495.0,Super Built up area 2905(269.88 sq.m.)Carpet a...,4,5,...,servant room,"2204, Sector 72 Gurgaon, Gurgaon, Haryana",22.0,West,1 to 5 Year Old,"['Sector 55-56 Metro Station', 'Omaxe City Cen...",This lovely 4 bhk apartment/flat in sector 72 ...,"['1 Water Purifier', '1 Exhaust Fan', '6 Geyse...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area4 out of 5', 'Construction4 out of..."

In [ ]:
df['sector'] = df['sector'].str.lower()

In [ ]:
df['sector'].value_counts()

sector
sohna                        163
sector 102                   113
sector 85                    110
sector 92                    104
sector 69                     94
                            ...
sector 17c                     1
godrej aria , sector 79 ,      1
new jyoti park                 1
kheri                          1
om nagar                       1
Name: count, Length: 301, dtype: int64

In [ ]:

df['sector'] = df['sector'].str.replace('dharam colony','sector 12')
df['sector'] = df['sector'].str.replace('krishna colony','sector 7')
df['sector'] = df['sector'].str.replace('suncity','sector 54')
df['sector'] = df['sector'].str.replace('prem nagar','sector 13')
df['sector'] = df['sector'].str.replace('mg road','sector 28')
df['sector'] = df['sector'].str.replace('gandhi nagar','sector 28')
df['sector'] = df['sector'].str.replace('laxmi garden','sector 11')
df['sector'] = df['sector'].str.replace('shakti nagar','sector 11')

In [ ]:
df['sector'] = df['sector'].str.replace('baldev nagar','sector 7')
df['sector'] = df['sector'].str.replace('shivpuri','sector 7')
df['sector'] = df['sector'].str.replace('garhi harsaru','sector 17')
df['sector'] = df['sector'].str.replace('imt manesar','manesar')
df['sector'] = df['sector'].str.replace('adarsh nagar','sector 12')
df['sector'] = df['sector'].str.replace('shivaji nagar','sector 11')
df['sector'] = df['sector'].str.replace('bhim nagar','sector 6')
df['sector'] = df['sector'].str.replace('madanpuri','sector 7')

In [ ]:
df['sector'] = df['sector'].str.replace('saraswati vihar','sector 28')
df['sector'] = df['sector'].str.replace('arjun nagar','sector 8')
df['sector'] = df['sector'].str.replace('ravi nagar','sector 9')
df['sector'] = df['sector'].str.replace('vishnu garden','sector 105')
df['sector'] = df['sector'].str.replace('bhondsi','sector 11')
df['sector'] = df['sector'].str.replace('surya vihar','sector 21')
df['sector'] = df['sector'].str.replace('devilal colony','sector 9')
df['sector'] = df['sector'].str.replace('valley view estate','gwal pahari')

In [ ]:
df['sector'] = df['sector'].str.replace('mehrauli  road','sector 14')
df['sector'] = df['sector'].str.replace('jyoti park','sector 7')
df['sector'] = df['sector'].str.replace('ansal plaza','sector 23')
df['sector'] = df['sector'].str.replace('dayanand colony','sector 6')
df['sector'] = df['sector'].str.replace('sushant lok phase 2','sector 55')
df['sector'] = df['sector'].str.replace('chakkarpur','sector 28')
df['sector'] = df['sector'].str.replace('greenwood city','sector 45')
df['sector'] = df['sector'].str.replace('subhash nagar','sector 12')

In [ ]:

df['sector'] = df['sector'].str.replace('sohna road road','sohna road')
df['sector'] = df['sector'].str.replace('malibu town','sector 47')
df['sector'] = df['sector'].str.replace('surat nagar 1','sector 104')
df['sector'] = df['sector'].str.replace('new colony','sector 7')
df['sector'] = df['sector'].str.replace('mianwali colony','sector 12')
df['sector'] = df['sector'].str.replace('jacobpura','sector 12')
df['sector'] = df['sector'].str.replace('rajiv nagar','sector 13')
df['sector'] = df['sector'].str.replace('ashok vihar','sector 3')

In [ ]:
df['sector'] = df['sector'].str.replace('dlf phase 1','sector 26')
df['sector'] = df['sector'].str.replace('nirvana country','sector 50')
df['sector'] = df['sector'].str.replace('palam vihar','sector 2')
df['sector'] = df['sector'].str.replace('dlf phase 2','sector 25')
df['sector'] = df['sector'].str.replace('sushant lok phase 1','sector 43')
df['sector'] = df['sector'].str.replace('laxman vihar','sector 4')
df['sector'] = df['sector'].str.replace('dlf phase 4','sector 28')
df['sector'] = df['sector'].str.replace('dlf phase 3','sector 24')

In [ ]:
df['sector'] = df['sector'].str.replace('sushant lok phase 3','sector 57')
df['sector'] = df['sector'].str.replace('dlf phase 5','sector 43')
df['sector'] = df['sector'].str.replace('rajendra park','sector 105')
df['sector'] = df['sector'].str.replace('uppals southend','sector 49')
df['sector'] = df['sector'].str.replace('sohna','sohna road')
df['sector'] = df['sector'].str.replace('ashok vihar phase 3 extension','sector 5')
df['sector'] = df['sector'].str.replace('south city 1','sector 41')
df['sector'] = df['sector'].str.replace('ashok vihar phase 2','sector 5')

In [ ]:
a = df['sector'].value_counts()[df['sector'].value_counts() >= 3]
df = df[df['sector'].isin(a.index)]

In [ ]:
df['sector'].value_counts()

sector
sohna road     163
sector 102     113
sector 85      110
sector 92      104
sector 69       94
              ...
sector 17a       3
sector 73        3
sector 17b       3
sector 15        3
patel nagar      3
Name: count, Length: 131, dtype: int64

In [ ]:
df['sector'] = df['sector'].str.replace('sector 95a','sector 95')
df['sector'] = df['sector'].str.replace('sector 23a','sector 23')
df['sector'] = df['sector'].str.replace('sector 12a','sector 12')
df['sector'] = df['sector'].str.replace('sector 3a','sector 3')
df['sector'] = df['sector'].str.replace('sector 110 a','sector 110')
df['sector'] = df['sector'].str.replace('patel nagar','sector 15')
df['sector'] = df['sector'].str.replace('a block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('maruti kunj','sector 12')
df['sector'] = df['sector'].str.replace('b block sector 43','sector 43')

In [ ]:
df['sector'] = df['sector'].str.replace('sector-33 sohna road','sector 33')
df['sector'] = df['sector'].str.replace('sector 1 manesar','manesar')
df['sector'] = df['sector'].str.replace('sector 4 phase 2','sector 4')
df['sector'] = df['sector'].str.replace('sector 1a manesar','manesar')
df['sector'] = df['sector'].str.replace('c block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector 89 a','sector 89')
df['sector'] = df['sector'].str.replace('sector 2 extension','sector 2')
df['sector'] = df['sector'].str.replace('sector 36 sohna road','sector 36')

In [ ]:
df[df['sector'] == 'new']

,property_name,property_type,society,sector,price,price_per_sqfeet,area,areaWithType,bedRoom,bathroom,...,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
473,4 BHK Flat in New Gurgaon,flats,dlf 76,new,4.00,11428.0,3500.0,Carpet area: 3500 (325.16 sq.m.),4,4,...,"study room,servant room","New Gurgaon, Gurgaon, Haryana",4.0,NaN,2027-06-01 00:00:00,"['Shri Balaji Hospital and Trauma Center', 'S....",This lovely 4 bhk apartment/flat in new gurgao...,"['6 Wardrobe', '1 Fridge', '8 Fan', '1 Exhaust...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN
1330,4 BHK Flat in New Gurgaon,flats,sare homes,new,0.85,4786.0,1776.0,Super Built up area 1776(165 sq.m.),4,4,...,not_available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,5 to 10 Year Old,"['Columbia Asia Hospital', 'Apex Multi Special...",Located in the popular residential address of ...,[],NaN,NaN
1598,2 BHK Flat in New Gurgaon,flats,takshila heights sector 37 c,new,0.67,5583.0,1200.0,Super Built up area 1200(111.48 sq.m.),2,2,...,not_available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,1 to 5 Year Old,"['Shri Balaji Hospital and Trauma Center', 'S....",Check out this 2 bhk apartment for sale in tak...,[],"['Lift(s)', 'Swimming Pool', 'Visitor Parking'...",NaN
2339,2 BHK Flat in New Gurgaon,flats,green court,new,0.38,5507.0,690.0,Carpet area: 690 (64.1 sq.m.),2,2,...,not_available,"New Gurgaon, Gurgaon, Haryana",7.0,NaN,Under Construction,"['Ing bank ATM', 'Dcb bank ATM', 'Indus ind ba...",We are the proud owners of this 2 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...",NaN

In [ ]:
df.loc[1598,'sector'] = 'sector 37'
df.loc[1330,'sector'] = 'sector 92'
df.loc[2339,'sector'] = 'sector 90'
df.loc[473,'sector'] = 'sector 76'

In [ ]:
df[df['sector'] == 'new sector 2']

,property_name,property_type,society,sector,price,price_per_sqfeet,area,areaWithType,bedRoom,bathroom,...,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
1013,2 Bedroom House for sale in New Palam Vihar,house,my home,new sector 2,0.34,NaN,270.0,Plot area 270(25.08 sq.m.),2,2,...,not available,"Ez-19 A, New Palam Vihar, Gurgaon, Haryana",3.0,West,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",There are availability of various facilities l...,"['1 Wardrobe', '3 Fan', '6 Light', 'No AC', 'N...","['Water Storage', 'Park', 'Visitor Parking']","['Environment4 out of 5', 'Lifestyle4 out of 5..."
1057,3 Bedroom House for sale in New Palam Vihar,house,Independent,new sector 2,1.00,NaN,1137.0,Plot area 120(100.34 sq.m.)Built Up area: 120 ...,3,2,...,pooja room,"Q-148, New Palam Vihar, Phase-2, Near Royal Oa...",1.0,North,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","Ground and first floor, Ground floor: Ground f...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
2380,2 BHK Flat in New Palam Vihar,flats,my home,new sector 2,0.28,3166.0,884.0,Carpet area: 900 (83.61 sq.m.),2,1,...,others,"F 150/b, New Palam Vihar, Gurgaon, Haryana",2.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","2 bhk room with wooden coverd ,1 drawing room,...","['3 Wardrobe', '5 Light', '1 Chimney', '1 Modu...","['Water Storage', 'Park']","['Environment4 out of 5', 'Safety4 out of 5', ..."
3465,2 BHK Flat in New Palam Vihar,flats,ompee k s residency,new sector 2,1.60,26936.0,594.0,Carpet area: 66 (55.18 sq.m.),2,2,...,not_available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",We are the proud owners of this 2 bhk apartmen...,NaN,NaN,"['Environment4 out of 5', 'Safety4 out of 5', ..."
3562,2 BHK Flat in New Palam Vihar,flats,my home,new sector 2,0.22,4400.0,500.0,Carpet area: 500 (46.45 sq.m.),2,2,...,not_available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,0 to 1 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",Cctv surveillance are provided here. There is ...,"['3 Fan', '1 Exhaust Fan', '15 Light', '1 Modu...",NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."

In [ ]:
df.loc[[1013,1057,2380,3465,3562],'sector'] = 'sector 110'

In [ ]:
df.shape

(3803, 21)

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqfeet,area,areaWithType,bedRoom,bathroom,...,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 109 Gurgaon,house,international city by sobha phase 2,sector 109,7.00,NaN,5400.0,Plot area 600(501.68 sq.m.),5,6,...,servant room,"141, Sector 109 Gurgaon, Gurgaon, Haryana",2.0,West,1 to 5 Year Old,"['Dwarka Sector 21 Metro Station', 'Pacific D2...","Peaceful, private, premium, gated, duplex vill...",NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,2 BHK Flat in Sohna,flats,breez global hill view,sohna road,0.35,5600.0,625.0,Carpet area: 625 (58.06 sq.m.),2,2,...,not_available,"Sohna, Gurgaon, Haryana",14.0,NaN,1 to 5 Year Old,"['Huda City Centre', 'Omaxe City Centre', 'Nin...","Spacious rooms, well maintained facilities, ri...","['3 Fan', '1 Exhaust Fan', '4 Light', '1 Curta...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
2,2 BHK Flat in Sector-33 Sohna,flats,godrej nature plus,sector 33,1.07,7725.0,1385.0,Super Built up area 1385(128.67 sq.m.),2,2,...,not_available,"Sector-33 Sohna, Gurgaon, Haryana",14.0,North-East,2023-08-01 00:00:00,"['Signature Global Infinity Mall Sohna', 'Bads...",We are the proud owners of this 2 bhk apartmen...,[],"['Lift(s)', 'Maintenance Staff', 'Water Storag...",NaN
3,4 BHK Flat in Sector 60 Gurgaon,flats,ireo skyon,sector 60,3.60,12815.0,2809.0,Super Built up area 2809(260.96 sq.m.)Carpet a...,4,5,...,servant room,"Sector 60 Gurgaon, Gurgaon, Haryana",24.0,North-East,1 to 5 Year Old,"['Sector 55-56 Metro', 'Golf Course Extension'...","This 4 bhk flat is located in ireo skyon, whic...","['7 Wardrobe', '1 Water Purifier', '6 Fan', '1...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction5 out of..."
4,4 BHK Flat in Sector 72 Gurgaon,flats,tata primanti,sector 72,4.00,16032.0,2495.0,Super Built up area 2905(269.88 sq.m.)Carpet a...,4,5,...,servant room,"2204, Sector 72 Gurgaon, Gurgaon, Haryana",22.0,West,1 to 5 Year Old,"['Sector 55-56 Metro Station', 'Omaxe City Cen...",This lovely 4 bhk apartment/flat in sector 72 ...,"['1 Water Purifier', '1 Exhaust Fan', '6 Geyse...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area4 out of 5', 'Construction4 out of..."

In [ ]:
df.loc[df['sector'] == 'sohna road', 'sector'] = 'sector 36'

In [ ]:
df['sector'].value_counts()

sector
sector 36     174
sector 102    113
sector 85     110
sector 92     105
sector 69      94
             ...
sector 27       3
sector 73       3
sector 17a      3
sector 17b      3
sector 37       1
Name: count, Length: 112, dtype: int64

In [ ]:
df['sector'].value_counts()

sector
sector 36     174
sector 102    113
sector 85     110
sector 92     105
sector 69      94
             ...
sector 27       3
sector 73       3
sector 17a      3
sector 17b      3
sector 37       1
Name: count, Length: 112, dtype: int64

In [ ]:
# features to drop -> property_name, address, description, rating
df.drop(columns=['property_name', 'address', 'description', 'rating'],inplace=True)

In [ ]:
df.sample(5)

,property_type,society,sector,price,price_per_sqfeet,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features
1924,flats,ramprastha the edge towers,sector 37d,1.00,5649.0,1770.0,Super Built up area 1770(164.44 sq.m.),3,3,3+,not_available,13.0,NaN,5 to 10 Year Old,"['MDS Public School', 'St Pauls School', 'Sunc...",[],"['Power Back-up', 'Intercom Facility', 'Lift(s..."
441,house,unitech uniworld resorts,sector 33,9.50,NaN,4071.0,Plot area 500(418.06 sq.m.),5,7,3+,"pooja room,study room,servant room,store room",2.0,East,2023-12-01 00:00:00,"['Rajiv Chowk Mosque', 'Icici bank ATM', 'Stan...",NaN,"['Feng Shui / Vaastu Compliant', 'Maintenance ..."
3923,flats,emaar mgf emerald estate,sector 65,1.30,20602.0,631.0,Super Built up area 1020(94.76 sq.m.)Carpet ar...,2,2,2,study room,7.0,West,1 to 5 Year Old,"['Sector 53-54 Metro Station', 'Central Plaza ...",NaN,"['Private Garden / Terrace', 'Lift(s)', 'Maint..."
1780,flats,la vida by tata housing,sector 113,3.05,11338.0,2690.0,Super Built up area 2690(249.91 sq.m.)Built Up...,3,4,3,servant room,15.0,North-East,0 to 1 Year Old,"['Dwarka Sector 21', 'Pacific D21 Mall', 'Bajg...","['1 Geyser', 'No AC', 'No Bed', 'No Chimney', ...","['Water purifier', 'Centrally Air Conditioned'..."
3464,flats,ss the leaf,sector 85,1.17,6720.0,1741.0,Super Built up area 1741(161.74 sq.m.)Built Up...,2,3,3,others,10.0,South-East,1 to 5 Year Old,"['Sapphire 83 Mall', 'Dwarka Expressway', 'Cen...","['4 AC', 'No Bed', 'No Chimney', 'No Curtains'...","['Feng Shui / Vaastu Compliant', 'Security / F..."

In [ ]:
# feature engineering required -> areaWithType, additionalRoom, facing, agePossession, furnishDetails, features

In [ ]:
df.duplicated().sum()

np.int64(122)

In [ ]:
df.to_csv('gurgaon_properties_cleaned_v1.csv',index=False)